// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RotatedSecretDockerhubParameters defines the desired state of the resource.
type RotatedSecretDockerhubParameters struct {
	// Credentials to connect with: use-user-creds or use-target-creds
	// +optional
	AuthenticationCredentials *string `json:"authentication_credentials,omitempty"`
	// Whether to automatically rotate every rotation-interval days [true/false]
	// +optional
	AutoRotate *string `json:"auto_rotate,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Encryption key name for the secret value
	// +optional
	Key *string `json:"key,omitempty"`
	// Maximum number of versions
	// +optional
	MaxVersions *string `json:"max_versions,omitempty"`
	// Rotated secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// How many days before the rotation of the item would you like to be notified
	// +optional
	RotationEventIn *string `json:"rotation_event_in,omitempty"`
	// The hour of the rotation in UTC
	// +optional
	RotationHour *int64 `json:"rotation_hour,omitempty"`
	// Days between every automatic key rotation (1-365)
	// +optional
	RotationInterval *string `json:"rotation_interval,omitempty"`
	// Tags for the rotated secret
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name to associate
	// +kubebuilder:validation:Required
	TargetName string `json:"target_name"`
}

// RotatedSecretDockerhubObservation reflects the observed state from the upstream provider.
type RotatedSecretDockerhubObservation struct {
}

// RotatedSecretDockerhubSpec is the desired state of the resource.
type RotatedSecretDockerhubSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider RotatedSecretDockerhubParameters `json:"forProvider"`
}

// RotatedSecretDockerhubStatus reflects the observed state of the resource.
type RotatedSecretDockerhubStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider RotatedSecretDockerhubObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type RotatedSecretDockerhub struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec RotatedSecretDockerhubSpec `json:"spec"`
	Status RotatedSecretDockerhubStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type RotatedSecretDockerhubList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []RotatedSecretDockerhub `json:"items"`
}
