// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DynamicSecretOracleParameters defines the desired state of the resource.
type DynamicSecretOracleParameters struct {
	// Customize how temporary usernames are generated using go template
	// +optional
	CustomUsernameTemplate *string `json:"custom_username_template,omitempty"`
	// Database server certificates (PEM)
	// +optional
	DbServerCertificates *string `json:"db_server_certificates,omitempty"`
	// Database server name for TLS verification
	// +optional
	DbServerName *string `json:"db_server_name,omitempty"`
	// Enable delete protection
	// +optional
	DeleteProtection *bool `json:"delete_protection,omitempty"`
	// Description of the object
	// +optional
	Description *string `json:"description,omitempty"`
	// Additional custom fields to associate with the item
	// +optional
	ItemCustomFields *string `json:"item_custom_fields,omitempty"`
	// Dynamic secret name
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="field is immutable"
	Name string `json:"name"`
	// Oracle host
	// +optional
	OracleHost *string `json:"oracle_host,omitempty"`
	// Oracle admin password
	// +optional
	OraclePassword *string `json:"oracle_password,omitempty"`
	// Oracle port (default: 1521)
	// +optional
	OraclePort *string `json:"oracle_port,omitempty"`
	// Oracle revocation statements
	// +optional
	OracleRevocationStatements *string `json:"oracle_revocation_statements,omitempty"`
	// Oracle Creation statements
	// +optional
	OracleScreationStatements *string `json:"oracle_screation_statements,omitempty"`
	// Oracle service name
	// +optional
	OracleServiceName *string `json:"oracle_service_name,omitempty"`
	// Oracle admin username
	// +optional
	OracleUsername *string `json:"oracle_username,omitempty"`
	// The length of the password to be generated
	// +optional
	PasswordLength *string `json:"password_length,omitempty"`
	// Dynamic producer encryption key
	// +optional
	ProducerEncryptionKeyName *string `json:"producer_encryption_key_name,omitempty"`
	// Tags for the producer
	// +optional
	Tags *string `json:"tags,omitempty"`
	// Target name associated with this producer
	// +optional
	TargetName *string `json:"target_name,omitempty"`
	// User TTL (e.g., 60m, 12h)
	// +optional
	UserTtl *string `json:"user_ttl,omitempty"`
}

// DynamicSecretOracleObservation reflects the observed state from the upstream provider.
type DynamicSecretOracleObservation struct {
}

// DynamicSecretOracleSpec is the desired state of the resource.
type DynamicSecretOracleSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider DynamicSecretOracleParameters `json:"forProvider"`
}

// DynamicSecretOracleStatus reflects the observed state of the resource.
type DynamicSecretOracleStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider DynamicSecretOracleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,akeyless,managed}
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
type DynamicSecretOracle struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec DynamicSecretOracleSpec `json:"spec"`
	Status DynamicSecretOracleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type DynamicSecretOracleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []DynamicSecretOracle `json:"items"`
}
