// Code generated by iac-forge. DO NOT EDIT.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

func (in *DynamicSecretOracle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretOracle) DeepCopy() *DynamicSecretOracle {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretOracle)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretOracle) DeepCopyInto(out *DynamicSecretOracle) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

func (in *DynamicSecretOracleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynamicSecretOracleList) DeepCopy() *DynamicSecretOracleList {
	if in == nil {
		return nil
	}
	out := new(DynamicSecretOracleList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynamicSecretOracleList) DeepCopyInto(out *DynamicSecretOracleList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DynamicSecretOracle, len(in.Items))
		for i := range in.Items {
			(&in.Items[i]).DeepCopyInto(&out.Items[i])
		}
	}
}
