// Code generated by iac-forge. DO NOT EDIT.

package eventforwarderemail

import (
	"context"
	"errors"
	"time"

	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/logging"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	akeyless "github.com/pleme-io/akeyless-go"
	providerv1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/akeyless/v1alpha1"
	v1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/eventforwarderemail/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// external is the per-cluster reconciler that owns the SDK client and
// the token resolved from the bound ProviderConfig.
type external struct {
	client *akeyless.APIClient
	token string
}

// Setup wires this resource's controller into the manager.
func Setup(mgr ctrl.Manager, pollInterval time.Duration) error {
	name := "EventForwarderEmail"
	gvk := v1alpha1.GroupVersion.WithKind("EventForwarderEmail")
	r := managed.NewReconciler(mgr, resource.ManagedKind(gvk), managed.WithExternalConnecter(&connector{
		kube: mgr.GetClient(),
	}), managed.WithPollInterval(pollInterval), managed.WithLogger(logging.NewLogrLogger(ctrl.Log.WithName(name))))
	return ctrl.NewControllerManagedBy(mgr).Named(name).For(&v1alpha1.EventForwarderEmail{}).Complete(r)
}

// connector resolves a ProviderConfig and constructs an external
// client for each managed-resource reconcile loop.
type connector struct {
	kube client.Client
}

func (c *connector) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*v1alpha1.EventForwarderEmail)
	if !ok {
		return nil, errors.New("expected *v1alpha1.EventForwarderEmail")
	}
	pcRef := cr.GetProviderConfigReference()
	if pcRef == nil {
		return nil, errors.New("no provider config reference")
	}

	pc := &providerv1alpha1.ProviderConfig{}
	if err := c.kube.Get(ctx, client.ObjectKey{
	Name: pcRef.Name,
}, pc); err != nil {
		return nil, err
	}
	creds, err := resource.CommonCredentialExtractor(ctx, pc.Spec.Credentials.Source, c.kube, pc.Spec.Credentials.CommonCredentialSelectors)
	if err != nil {
		return nil, err
	}

	cfg := akeyless.NewConfiguration()
	if pc.Spec.APIGateway != "" {
		// TODO goast-slice-2: emit cfg.Servers via structured SliceLit
		cfg.Servers = []akeyless.ServerConfiguration{{URL: pc.Spec.APIGateway}}
	}
	return &external{
		client: akeyless.NewAPIClient(cfg),
		token: string(creds),
	}, nil
}

// Observe queries the upstream provider for the resource's current state.
// The returned ExternalObservation tells the managed-resource reconciler
// (a) whether the resource exists upstream and (b) whether its observed
// state matches the declared spec.
func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.EventForwarderEmail)
	if !ok {
		return managed.ExternalObservation{}, errors.New("expected *v1alpha1.EventForwarderEmail")
	}

	body := akeyless.GetEventForwarder{
		Name: meta.GetExternalName(cr),
		Token: &e.token,
	}
	_, _, err := e.client.V2API.GetEventForwarder(ctx).GetEventForwarder(body).Execute()
	if err != nil {
		// TODO controller-iter-2: distinguish 404 (NotFound → ResourceExists=false)
		// from real errors; today every read error short-circuits the reconcile.
		return managed.ExternalObservation{}, err
	}

	cr.SetConditions(xpv1.Available())
	// ResourceUpToDate=true short-circuits the spec↔atProvider diff;
	// structural diff lands in controller-iter-2.
	return managed.ExternalObservation{
		ResourceExists: true,
		ResourceUpToDate: true,
	}, nil
}

// Create provisions the resource upstream.
func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.EventForwarderEmail)
	if !ok {
		return managed.ExternalCreation{}, errors.New("expected *v1alpha1.EventForwarderEmail")
	}

	body := akeyless.EventForwarderCreateEmail{
		Name: meta.GetExternalName(cr),
		Token: &e.token,
	}
	// TODO controller-iter-2: map cr.Spec.ForProvider fields → body fields
	_, _, err := e.client.V2API.EventForwarderCreateEmail(ctx).EventForwarderCreateEmail(body).Execute()
	return managed.ExternalCreation{}, err
}

// Update reconciles the upstream resource against the declared spec.
func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.EventForwarderEmail)
	if !ok {
		return managed.ExternalUpdate{}, errors.New("expected *v1alpha1.EventForwarderEmail")
	}

	body := akeyless.EventForwarderUpdateEmail{
		Name: meta.GetExternalName(cr),
		Token: &e.token,
	}
	// TODO controller-iter-2: map mutable cr.Spec.ForProvider fields → body fields
	_, _, err := e.client.V2API.EventForwarderUpdateEmail(ctx).EventForwarderUpdateEmail(body).Execute()
	return managed.ExternalUpdate{}, err
}

// Delete removes the upstream resource. Idempotent on NotFound.
// Signature follows crossplane-runtime v1.18+: returns (ExternalDelete, error).
func (e *external) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.EventForwarderEmail)
	if !ok {
		return managed.ExternalDelete{}, errors.New("expected *v1alpha1.EventForwarderEmail")
	}

	body := akeyless.EventForwarderDelete{
		Name: meta.GetExternalName(cr),
		Token: &e.token,
	}
	_, _, err := e.client.V2API.EventForwarderDelete(ctx).EventForwarderDelete(body).Execute()
	// TODO controller-iter-2: swallow 404 so deletion is idempotent.
	return managed.ExternalDelete{}, err
}

// Disconnect releases any per-cluster client resources. The akeyless SDK
// holds no long-lived resources beyond per-call request state, so this is
// a no-op. Required by crossplane-runtime v1.18+'s ExternalClient interface.
func (_ *external) Disconnect(_ context.Context) error {
	return nil
}
