// Code generated by iac-forge. DO NOT EDIT.

package policy

import (
	"context"
	"errors"
	"time"

	"github.com/crossplane/crossplane-runtime/pkg/logging"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	akeyless "github.com/pleme-io/akeyless-go"
	providerv1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/akeyless/v1alpha1"
	v1alpha1 "github.com/pleme-io/crossplane-akeyless/apis/policy/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// external is the per-cluster reconciler that owns the SDK client and
// the token resolved from the bound ProviderConfig.
type external struct {
	client *akeyless.APIClient
	token string
}

// Setup wires this resource's controller into the manager.
func Setup(mgr ctrl.Manager, pollInterval time.Duration) error {
	name := "Policy"
	gvk := v1alpha1.GroupVersion.WithKind("Policy")
	r := managed.NewReconciler(mgr, resource.ManagedKind(gvk), managed.WithExternalConnecter(&connector{
		kube: mgr.GetClient(),
	}), managed.WithPollInterval(pollInterval), managed.WithLogger(logging.NewLogrLogger(ctrl.Log.WithName(name))))
	return ctrl.NewControllerManagedBy(mgr).Named(name).For(&v1alpha1.Policy{}).Complete(r)
}

// connector resolves a ProviderConfig and constructs an external
// client for each managed-resource reconcile loop.
type connector struct {
	kube client.Client
}

func (c *connector) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*v1alpha1.Policy)
	if !ok {
		return nil, errors.New("expected *v1alpha1.Policy")
	}
	pcRef := cr.GetProviderConfigReference()
	if pcRef == nil {
		return nil, errors.New("no provider config reference")
	}

	pc := &providerv1alpha1.ProviderConfig{}
	if err := c.kube.Get(ctx, client.ObjectKey{
	Name: pcRef.Name,
}, pc); err != nil {
		return nil, err
	}
	creds, err := resource.CommonCredentialExtractor(ctx, pc.Spec.Credentials.Source, c.kube, pc.Spec.Credentials.CommonCredentialSelectors)
	if err != nil {
		return nil, err
	}

	cfg := akeyless.NewConfiguration()
	if pc.Spec.APIGateway != "" {
		// TODO goast-slice-2: emit cfg.Servers via structured SliceLit
		cfg.Servers = []akeyless.ServerConfiguration{{URL: pc.Spec.APIGateway}}
	}
	return &external{
		client: akeyless.NewAPIClient(cfg),
		token: string(creds),
	}, nil
}

// Observe — STUB. Body-mapping pending M3.2 graduation for resources whose
// SDK body shape requires composite keys / mixed-per-CRUD identifiers.
// Returns an empty ExternalObservation so the reconciler stays idle.
func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	_, ok := mg.(*v1alpha1.Policy)
	if !ok {
		return managed.ExternalObservation{}, errors.New("expected *v1alpha1.Policy")
	}

	// Stub: body-mapping pending M3.2 graduation — returns ResourceExists=false
	// so the reconciler stays idle for resources with composite-key shapes.
	return managed.ExternalObservation{}, nil
}

// Create — STUB. Body-mapping pending M3.2 graduation.
func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	_, ok := mg.(*v1alpha1.Policy)
	if !ok {
		return managed.ExternalCreation{}, errors.New("expected *v1alpha1.Policy")
	}

	// Stub: body-mapping pending M3.2 graduation.
	return managed.ExternalCreation{}, nil
}

// Update — STUB. Body-mapping pending M3.2 graduation.
func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	_, ok := mg.(*v1alpha1.Policy)
	if !ok {
		return managed.ExternalUpdate{}, errors.New("expected *v1alpha1.Policy")
	}

	// Stub: body-mapping pending M3.2 graduation.
	return managed.ExternalUpdate{}, nil
}

// Delete — STUB. Body-mapping pending M3.2 graduation.
func (e *external) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	_, ok := mg.(*v1alpha1.Policy)
	if !ok {
		return managed.ExternalDelete{}, errors.New("expected *v1alpha1.Policy")
	}
	// Stub: body-mapping pending M3.2 graduation.
	return managed.ExternalDelete{}, nil
}

// Disconnect releases any per-cluster client resources. The akeyless SDK
// holds no long-lived resources beyond per-call request state, so this is
// a no-op. Required by crossplane-runtime v1.18+'s ExternalClient interface.
func (_ *external) Disconnect(_ context.Context) error {
	return nil
}
